name: Build all platforms

on:
  workflow_dispatch:

jobs:
  linux:
    uses: ./.github/workflows/build-linux.yml
    permissions:
      contents: write

  macos:
    uses: ./.github/workflows/build-macos.yml
    permissions:
      contents: write

  windows:
    uses: ./.github/workflows/build-windows.yml
    permissions:
      contents: write

  tauri-linux:
    uses: ./.github/workflows/tauri-build-linux.yml
    permissions:
      contents: write

  tauri-macos:
    uses: ./.github/workflows/tauri-build-macos.yml
    permissions:
      contents: write

  tauri-windows:
    uses: ./.github/workflows/tauri-build-windows.yml
    permissions:
      contents: write
