name: Build all platforms

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  tauri-linux:
    uses: ./.github/workflows/tauri-build-linux.yml
    with:
      publish: ${{ github.event_name == 'release' }}
    permissions:
      contents: write

  tauri-macos:
    uses: ./.github/workflows/tauri-build-macos.yml
    with:
      publish: ${{ github.event_name == 'release' }}
    permissions:
      contents: write

  tauri-windows:
    uses: ./.github/workflows/tauri-build-windows.yml
    with:
      publish: ${{ github.event_name == 'release' }}
    permissions:
      contents: write
